# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# contact rules
contact:
  url:      /
  class:    sfDoctrineRoute
  options:  { model: Contact, type: object }
  param:    { module: contact, action: list }

contact_show:
  url:      /show/:id
  class:    sfDoctrineRoute
  options:  { model: Contact, type: object }
  param:    { module: contact, action: show }

contact_edit:
  url:      /edit/:id
  class:    sfDoctrineRoute
  options:  { model: Contact, type: object }
  param:    { module: contact, action: edit }

contact_update:
  url:      /update/:id
  class:    sfDoctrineRoute
  options:  { model: Contact, type: object }
  param:    { module: contact, action: update }

# note rules
note_show:
  url:      /show/:contact_id/note/:id
  class:    sfDoctrineRoute
  options:  { model: Note, type: object }
  param:    { module: note, action: show }