# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# project rules
contact:
  url:      /
  class:    sfDoctrineRoute
  options:  { model: Contact, type: object }
  param:    { module: contact, action: list }

contact_show:
  url:      /show/:id
  class:    sfDoctrineRoute
  options:  { model: Contact, type: object }
  param:    { module: contact, action: show }
  
note_show:
  url:      /show/:contact_id/note/:id
  class:    sfDoctrineRoute
  options:  { model: Note, type: object }
  param:    { module: note, action: show }